backend: dp
type: Hybrid_ULRSSM_Model
num_gpu: auto
manual_seed: 1234
non-isometric: false
partial: false
n_lb: 140
n_elas: 60
path:
  resume_state:

# datasets
datasets:
  train_dataset:
    name: Train
    type: PairTopKidsDataset
    phase: train
    data_root: ../data/TOPKIDS/
    return_evecs: true
    return_faces: true
    num_evecs: 200
    return_dist: false
    return_elas_evecs: true
    bending_weight: 0.01
  test_dataset:
    name: Test
    type: PairTopKidsDataset
    phase: test
    data_root: ../data/TOPKIDS/
    return_evecs: true
    return_faces: true
    num_evecs: 200
    return_dist: true
    return_elas_evecs: true
    bending_weight: 0.01
  batch_size: 1
  num_worker: 12

# network setting
networks:
  feature_extractor:
    type: DiffusionNet
    in_channels: 128
    out_channels: 256
    cache_dir: ../data/TOPKIDS/diffusion
    input_type: wks
  fmap_net:
    type: RegularizedFMNet
    bidirectional: true
  expanded_fmap_net:
    type: ExpandedResolventFMNet
    lmbda: 50
    bidirectional: true
  permutation:
    type: Similarity
    tau: 0.07

# training setting
train:
  total_epochs: 100
  weight_schedule: 2000
  optims:
    feature_extractor:
      type: Adam
      lr: 1.0e-3
  schedulers:
    feature_extractor:
      type: CosineAnnealingLR
      eta_min: 1.0e-4
      T_max: 100
  losses:
    surfmnet_loss:
      type: SURFMNetLoss
      w_bij: 1.0
      w_orth: 1.0
      w_lap: 0.0
    hs_surfmnet_loss:
      type: HS_SURFMNetLoss
      w_bij: 1.0
      w_orth: 0.0
      w_lap: 0.0
    align_loss:
      type: SquaredFrobeniusLoss
      loss_weight: 1.0
    hs_align_loss:
      type: SquaredHilbertSchmidtLoss
      loss_weight: 1.0
val:
  val_freq: 4000
  metrics:
    geo_error:
      type: calculate_geodesic_error
    plot_pck:
      type: plot_pck

# log setting
logger:
  print_freq: 20
  save_checkpoint_freq: 4000
