backend: dp
type: Hybrid_GeomFmaps_Model
num_gpu: auto
manual_seed: 1234
n_lb: 20
n_elas: 10
path:
  resume_state:

# datasets
datasets:
  train_dataset:
    name: FaustTrain
    type: PairFaustDataset
    phase: train
    data_root: ../data/FAUST_r
    return_evecs: true
    return_faces: true
    num_evecs: 30
    return_corr: true
    return_dist: false
    return_elas_evecs: true
    bending_weight: 0.01
  test_dataset:
    name: FaustTest
    type: PairFaustDataset
    phase: test
    data_root: ../data/FAUST_r
    return_evecs: true
    return_faces: true
    num_evecs: 30
    return_corr: true
    return_dist: true
    return_elas_evecs: true
    bending_weight: 0.01
  batch_size: 1
  num_worker: 12

# network setting
networks:
  feature_extractor:
    type: DiffusionNet
    in_channels: 128
    out_channels: 256
    cache_dir: ../data/FAUST_r/diffusion
    input_type: wks
  fmap_net:
    type: StandardFMNet
    bidirectional: false
  expanded_fmap_net:
    type: ExpandedStandardFMNet
    lmbda: 0.0005
    bidirectional: false
train:
  total_epochs: 10
  weight_schedule: 2000
  optims:
    feature_extractor:
      type: Adam
      lr: 1.0e-3
  schedulers:
    feature_extractor:
      type: StepLR
      step_size: 5
      gamma: 0.1

  losses:
    gt_loss:
      type: SquaredFrobeniusLoss
      loss_weight: 1.0
    elas_gt_loss:
      type: SquaredHilbertSchmidtLoss
      loss_weight: 1.0
val:
  val_freq: 4000
  metrics:
    geo_error:
      type: calculate_geodesic_error
    plot_pck:
      type: plot_pck

# log setting
logger:
  print_freq: 20
  save_checkpoint_freq: 4000
